export const PROFILE_MESSAGE_LOADING = 'PROFILE_MESSAGE_LOADING'
export const PROFILE_MESSAGE_SUCCESS = 'PROFILE_MESSAGE_SUCCESS'
export const PROFILE_MESSAGE_ERROR = 'PROFILE_MESSAGE_ERROR'
export const PROFILE_MESSAGE_UPDATE = 'PROFILE_MESSAGE_UPDATE'

